### Today Concepts
- **Comprehensions**
- **Introduction to DS**
- **Numpy module**
- comprehension in general refers to a short paragragh describing something
- Comprehension means shortening the no.of lines of code
- **syntax**
    - [output input_sequence condition_check]
- 2 comprehensions
    - list,dict comprehensions
    - {ouput input condition}

In [10]:
# prepare a list of square values of numbers 
# present in a range
sq=[]
lw,up=int(input()),int(input())
for num in range(lw,up+1):
    # append the squares of numbers
    sq.append(num**2)
print(sq)

1
20
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [11]:
#using list comprehension
li=[num**2 for num in  range(int(input()),int(input()))]
print(li)

1
15
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]


In [12]:
[num**2 for num in range(1,10)] # 

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
# print the multiplication table using list comp 
n=int(input())
mul=[print(n,'x',num,'=',n*num) for num in range(1,11)]

9
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


In [14]:
# prepare a list of characters 
# whose ascii value is even in a string
# string:i/p
#o/p:s=input()
a=input()
sq=[]
for i in range(0,len(a)):
    if ord(a[i])%2==0:
        sq.append(i) # nums 
print(sq)

string
[1, 2, 4]


In [15]:
chars=[]
for ch in input():
    if ord(ch)%2==0: # int
        print(ch,":",ord(ch))
        chars.append(ch)
chars

string
t : 116
r : 114
n : 110


['t', 'r', 'n']

In [16]:
s=[ch for ch in input() if ord(ch)%2 is 0]
print(s)

string
['t', 'r', 'n']


In [17]:
chr(65) # char of a number

'A'

In [18]:
ord('A')

65

#### Dictionary Comprehension

In [8]:
# prepare a dict of cubic values of no.s 
# present in a range
dic={}
for num in range(1,20):
    dic[num]=num**3
print(dic)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000, 11: 1331, 12: 1728, 13: 2197, 14: 2744, 15: 3375, 16: 4096, 17: 4913, 18: 5832, 19: 6859}


In [3]:
# using comprehension
cubes={num:num**3 for num in range(1,15)}
print(cubes)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000, 11: 1331, 12: 1728, 13: 2197, 14: 2744}


In [6]:
# prepare a char dict of numbers present in a range
# 50 to 100:{characters}
c={}
for num in range(65,100):
    c[num]=chr(num)
print(c)

{65: 'A', 66: 'B', 67: 'C', 68: 'D', 69: 'E', 70: 'F', 71: 'G', 72: 'H', 73: 'I', 74: 'J', 75: 'K', 76: 'L', 77: 'M', 78: 'N', 79: 'O', 80: 'P', 81: 'Q', 82: 'R', 83: 'S', 84: 'T', 85: 'U', 86: 'V', 87: 'W', 88: 'X', 89: 'Y', 90: 'Z', 91: '[', 92: '\\', 93: ']', 94: '^', 95: '_', 96: '`', 97: 'a', 98: 'b', 99: 'c'}


In [7]:
cr={num:chr(num) for num in range(50,100)}
print(cr)

{50: '2', 51: '3', 52: '4', 53: '5', 54: '6', 55: '7', 56: '8', 57: '9', 58: ':', 59: ';', 60: '<', 61: '=', 62: '>', 63: '?', 64: '@', 65: 'A', 66: 'B', 67: 'C', 68: 'D', 69: 'E', 70: 'F', 71: 'G', 72: 'H', 73: 'I', 74: 'J', 75: 'K', 76: 'L', 77: 'M', 78: 'N', 79: 'O', 80: 'P', 81: 'Q', 82: 'R', 83: 'S', 84: 'T', 85: 'U', 86: 'V', 87: 'W', 88: 'X', 89: 'Y', 90: 'Z', 91: '[', 92: '\\', 93: ']', 94: '^', 95: '_', 96: '`', 97: 'a', 98: 'b', 99: 'c'}


#### Data Science
- The study of data is called data science
- the data can exists in different formats in realtime
    - .txt,.c,.py,.mp3,.mp4 etc
- every row can be considered as sample 

#### Numpy
- Numpy stands for NumericalPython
- It is one of the most important and efficient modules of data science
- used for scientific computation and deal with array type of data
- *install the numpy in your local machine*
- import the features of numpy at workspace


In [19]:
import numpy as n

In [20]:
n.__version__ # version is attribute

'1.15.1'

#### Array creation
- array() is the submodule in numpy() module
- homogenous data structure and immutable

In [21]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [24]:
# creating the array using string
st=n.array(input().split()) # list of words
print(st)

I am ruthu from APSSDC
['I' 'am' 'ruthu' 'from' 'APSSDC']


In [25]:
type(st)

numpy.ndarray

In [26]:
# using range() method
print(n.array(range(10))) # array of no.s from 0 to 9

[0 1 2 3 4 5 6 7 8 9]


In [27]:
print(n.array(range(30,51)))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [28]:
print(n.array(range(30,100,6)))

[30 36 42 48 54 60 66 72 78 84 90 96]


In [29]:
# using tuple of numbers
print(n.array((1,4,6,7,8,'ruthu')))

['1' '4' '6' '7' '8' 'ruthu']


In [32]:
li=n.array([1,3,4,5,6])
print(li)

[1 3 4 5 6]


In [33]:
# 2d arrays using list of lists
dim=n.array([[1,2,3],[4,5,6]])
print(dim)

[[1 2 3]
 [4 5 6]]


In [34]:
# list of tuples
lt=n.array([(9,4,5),(9,1,2)])
print(lt)

[[9 4 5]
 [9 1 2]]


In [10]:
# tuple of lists
import numpy as n
tl=n.array(([1,2,'a'],[3,'b',4],[5,'c',6]))
print(tl)

[['1' '2' 'a']
 ['3' 'b' '4']
 ['5' 'c' '6']]


In [43]:
lt

array([[9, 4, 5],
       [9, 1, 2]])

In [39]:
lt.dtype # data type of each ele in array

dtype('int32')

In [40]:
lt.size # no.of elements in lt

6

In [45]:
tl.shape # (row,col)

(3, 3)

In [44]:
tl.itemsize # size of each element/item

44

#### creating the array using arange()
- works like range() in python
- arange(single)
- arange(start,stop)
- arange(st,sp,step)

In [48]:
print(n.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [50]:
print(n.arange(500,600))

[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535
 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553
 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571
 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589
 590 591 592 593 594 595 596 597 598 599]


In [51]:
print(n.arange(100,200,15))

[100 115 130 145 160 175 190]


##### reahape
- we can reshape the existed array()
- n.reshape(array)

In [6]:
### aabbbcccc
### o/p:2a3b4c and vice versa
s=input()
count=0
for index in range(len(s)):
    if s[index]==s[index+1]:
        count+=1
        print(count,s[index],end="")

aabbb
1 a2 b3 b

IndexError: string index out of range

In [4]:
# i/p:2a3b4c
# o/p:aabbbcccc
st=input()
for index in range(len(st)):
    if st[index].isdigit():
        print(int(st[index])*st[index+1],end="")

2a4c5g
aaccccggggg

In [2]:
3*"p"

'ppp'

In [3]:
st[1]

'a'

In [8]:
import numpy as np

In [16]:
ar=np.arange(24) # (1,24),(2,12),(6,4),(4,6)
print(ar.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [17]:
ar2=n.arange(40).reshape(8,5)
print(ar2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [18]:
help(n.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [22]:
pr=n.arange(10000).reshape(50,-6) # -ve value
print(pr)

[[   0    1    2 ...  197  198  199]
 [ 200  201  202 ...  397  398  399]
 [ 400  401  402 ...  597  598  599]
 ...
 [9400 9401 9402 ... 9597 9598 9599]
 [9600 9601 9602 ... 9797 9798 9799]
 [9800 9801 9802 ... 9997 9998 9999]]


In [24]:
pr2=n.arange(10000).reshape(-1,80) # -ve value
print(pr2)

[[   0    1    2 ...   77   78   79]
 [  80   81   82 ...  157  158  159]
 [ 160  161  162 ...  237  238  239]
 ...
 [9760 9761 9762 ... 9837 9838 9839]
 [9840 9841 9842 ... 9917 9918 9919]
 [9920 9921 9922 ... 9997 9998 9999]]


#### random 
- used to generate random values in a range
- random.randint()
- random.random()
- random.rand()
- random.randn()

In [33]:
print(np.random.randint(20)) # starts from 0

5


In [38]:
# no.of random values
np.random.randint(100,500)

430

In [42]:
np.random.randint(500,1000,9) # 9 random values

array([681, 760, 642, 968, 972, 894, 576, 872, 525])

In [44]:
# n random values
np.random.randint(1000,4000,int(input("Enter n value:")))

Enter n value:40


array([1062, 2489, 3342, 3903, 2706, 3271, 1682, 3789, 2898, 1188, 3793,
       3148, 3518, 3160, 1087, 2122, 3763, 1968, 3460, 1154, 3769, 2310,
       1937, 1868, 1049, 2779, 1117, 3654, 3572, 1732, 2547, 2452, 2452,
       1764, 1590, 2073, 2377, 3186, 3347, 3350])

In [56]:
# random.random() 
np.random.random(30)  # generates n floating random 
# int b/w 0 and 1

array([0.7835487 , 0.16785939, 0.98724384, 0.25272503, 0.45294813,
       0.61315194, 0.72143087, 0.75526498, 0.1598425 , 0.80015559,
       0.92404313, 0.28368444, 0.1923397 , 0.55208448, 0.57798968,
       0.06223634, 0.18837086, 0.49125546, 0.50308976, 0.42689418,
       0.91263678, 0.16052021, 0.12036201, 0.7826981 , 0.98981572,
       0.8969026 , 0.10328602, 0.43312537, 0.5937447 , 0.15475085])

In [61]:
# random.rand()
np.random.rand(4,3) #size of the array

array([[0.82125431, 0.36884543, 0.17561904],
       [0.64491814, 0.94125869, 0.86826348],
       [0.42041648, 0.67532137, 0.08550452],
       [0.91691141, 0.40404209, 0.34447632]])

In [65]:
np.random.randn(2,2) # from -1 to 1

array([[ 0.55355919,  0.10687594],
       [-1.35803786,  0.23183518]])

#### creating array using linear space()
- np.linspace()

In [68]:
np.linspace(2,6,10) # 3rd arg parition the given range

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [70]:
np.linspace(int(input()),int(input())) 
# 50 values will be generated by default b/w 5&10

10
40


array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [74]:
np.ones((4,5)) # ones matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [77]:
zeros=np.zeros((4,5)) # size of the array

In [78]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
i=np.eye(5) # identity matrix
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.diag(tl) # diagonal element of tl

array(['1', 'b', '6'], dtype='<U11')

In [81]:
tl

array([['1', '2', 'a'],
       ['3', 'b', '4'],
       ['5', 'c', '6']], dtype='<U11')

In [82]:
# we can create the diagonal matrix
d=np.diag([6,7,2,1])
d

array([[6, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

#### Accessing the array elements

In [86]:
ar2.shape

(8, 5)

In [87]:
ar2[0] # first row element

array([0, 1, 2, 3, 4])

In [89]:
ar2[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [91]:
ar2[::-1]

array([[35, 36, 37, 38, 39],
       [30, 31, 32, 33, 34],
       [25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [93]:
ar2[2:7]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [95]:
ar2[3:6,1:4] # slicing of both columns and rows

array([[16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [97]:
ar2[6][2] # 2d indexing

32

#### Fancy indexing
- condition based indexing

In [98]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [110]:
man=np.random.randint(40,200,16).reshape(4,-1)
man

array([[165, 188,  64,  53],
       [ 83, 158, 149,  71],
       [ 94, 104,  71, 194],
       [ 90, 178, 161, 169]])

In [112]:
# elements >150
man>150 #boolean array

array([[ True,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True],
       [False,  True,  True,  True]])

In [113]:
man[man>150] # int matrix

array([165, 188, 158, 194, 178, 161, 169])

#### Scientific Computation

In [114]:
# take 2 random arrays and perform 
# all the arithmetic op'ns on  both
r=np.arange(20,100,5).reshape(4,4)

In [115]:
r

array([[20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [116]:
man

array([[165, 188,  64,  53],
       [ 83, 158, 149,  71],
       [ 94, 104,  71, 194],
       [ 90, 178, 161, 169]])

In [119]:
print(r+man)
print(man-r)
print(man*r)
print(man//r)
print(man%r)

[[185 213  94  88]
 [123 203 199 126]
 [154 169 141 269]
 [170 263 251 264]]
[[145 163  34  18]
 [ 43 113  99  16]
 [ 34  39   1 119]
 [ 10  93  71  74]]
[[ 3300  4700  1920  1855]
 [ 3320  7110  7450  3905]
 [ 5640  6760  4970 14550]
 [ 7200 15130 14490 16055]]
[[8 7 2 1]
 [2 3 2 1]
 [1 1 1 2]
 [1 2 1 1]]
[[ 5 13  4 18]
 [ 3 23 49 16]
 [34 39  1 44]
 [10  8 71 74]]


In [120]:
print(man.min())

53


In [121]:
man.max()

194

In [122]:
man.sum()

1992

In [123]:
n.log(2) # logarithms

0.6931471805599453

In [124]:
np.log(10)

2.302585092994046

In [125]:
np.log2(2)

1.0

In [126]:
n.log([5,6,7]) # list of values

array([1.60943791, 1.79175947, 1.94591015])

In [127]:
help(n.log)

Help on ufunc object:

log = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [128]:
n.exp(5) # exponential func

148.4131591025766

In [129]:
n.exp(2)

7.38905609893065

In [131]:
n.exp(1)

2.718281828459045

In [133]:
n.exp([4,7,1]) # exp fun on list of values

array([  54.59815003, 1096.63315843,    2.71828183])

In [135]:
n.exp(n.log(3)) # exponential of log(3)

3.0000000000000004

In [136]:
n.log(n.log(5))

0.47588499532711054

In [138]:
n.log(n.exp(1))

1.0

In [139]:
n.exp(n.log(1))

1.0

#### vectorized functions in numpy

In [140]:
def greater(a,b):
    if a>b:
        return a
    else:return b
    
greater(9,10)

10

In [141]:
greater(11,6)

11

In [142]:
greater([6,7,1],[9,1,4])
# res=[9,7,4]

[9, 1, 4]

In [144]:
greater([10,4,3],[4,7,1]) # this works on first val of both lists

[10, 4, 3]

In [147]:
g=np.vectorize(greater)

In [149]:
g([6,7,1],[9,1,4]) # corresponding

array([9, 7, 4])

In [150]:
help(n.vectorize)

Help on class vectorize in module numpy.lib.function_base:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns an single or tuple of numpy array as
 |  output. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optiona

### Pandas
- PanelData
- data is in the form of rows and columns
- used to analyse,manipulate and clean the data 
- 2 data structures
    1. Series
        - sequence of data
        - pandas.Series(obj)
    2. DataFrame
        - data can be arranged in rows and columns
        - pandas.DataFrame(obj)

In [151]:
import pandas as pd

In [152]:
pd.__version__

'0.23.4'

In [155]:
pd.Series("I am from RVR&JC".split())

0         I
1        am
2      from
3    RVR&JC
dtype: object

In [156]:
pd.Series((4,5,7,8,9,'ruthu')) # tuple of items

0        4
1        5
2        7
3        8
4        9
5    ruthu
dtype: object

In [161]:
# dict into series
dic={1:"hi",2:"hey",3:'hello','four':'five'}
s=pd.Series(dic)
s

1          hi
2         hey
3       hello
four     five
dtype: object

In [162]:
# we can provide the user index to the series
s.index=[1,2,3,4]

In [163]:
s

1       hi
2      hey
3    hello
4     five
dtype: object

In [172]:
# create the series using range() and array()
a=np.arange(10,21)
sa=pd.Series(a)
sa

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int32

In [173]:
sa.index=[num for num in range(50,61)] # 10

In [174]:
sa

50    10
51    11
52    12
53    13
54    14
55    15
56    16
57    17
58    18
59    19
60    20
dtype: int32

In [176]:
sa.index[3] # 4th index value of series sa

53

In [180]:
sa[3:6] # slicing

53    13
54    14
55    15
dtype: int32

In [182]:
sa[::-1]

60    20
59    19
58    18
57    17
56    16
55    15
54    14
53    13
52    12
51    11
50    10
dtype: int32

In [183]:
sa[:7]

50    10
51    11
52    12
53    13
54    14
55    15
56    16
dtype: int32

In [184]:
sa[4:]

54    14
55    15
56    16
57    17
58    18
59    19
60    20
dtype: int32

#### Data Frames

In [187]:
std_dic={"year":[1,2,3,4],'dept':["cse",'ece','civil','mech'],
        "time":[8,9,10,7]}
df=pd.DataFrame(std_dic)
print(df)

   year   dept  time
0     1    cse     8
1     2    ece     9
2     3  civil    10
3     4   mech     7


In [188]:
df

year   dept  time
0     1    cse     8
1     2    ece     9
2     3  civil    10
3     4   mech     7

In [190]:
std={"year":[1,2,7,4],'dept':["cse",'ece','eee','mech'],
        "time":[8,9,12,7]}
df2=pd.DataFrame(std)
df2

year  dept  time
0     1   cse     8
1     2   ece     9
2     7   eee    12
3     4  mech     7

In [191]:
# merging two dfs
df.merge(df2) # non-similar row will be removed

year  dept  time
0     1   cse     8
1     2   ece     9
2     4  mech     7

In [195]:
dir(pd)

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'Interval',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseSeries',
 'Term',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt64Index',
 'WidePanel',
 '_DeprecatedModule',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_tslib',
 '_version',
 'api',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'descri

In [196]:
pd.concat([df,df2])

year   dept  time
0     1    cse     8
1     2    ece     9
2     3  civil    10
3     4   mech     7
0     1    cse     8
1     2    ece     9
2     7    eee    12
3     4   mech     7

In [198]:
df3=df+df2 # combines the both dfs
df3

year      dept  time
0     2    csecse    16
1     4    eceece    18
2    10  civileee    22
3     8  mechmech    14

In [200]:
df3.columns

Index(['year', 'dept', 'time'], dtype='object')

In [201]:
df3.columns[0]

'year'

In [202]:
df2

year  dept  time
0     1   cse     8
1     2   ece     9
2     7   eee    12
3     4  mech     7

In [204]:
m=pd.concat([df,df2])
m

year   dept  time
0     1    cse     8
1     2    ece     9
2     3  civil    10
3     4   mech     7
0     1    cse     8
1     2    ece     9
2     7    eee    12
3     4   mech     7

In [206]:
m.sample() # generate the random sample in our df

year dept  time
0     1  cse     8

In [207]:
m.head() # first five samples

year   dept  time
0     1    cse     8
1     2    ece     9
2     3  civil    10
3     4   mech     7
0     1    cse     8

In [208]:
m.tail() # last five samples

year  dept  time
3     4  mech     7
0     1   cse     8
1     2   ece     9
2     7   eee    12
3     4  mech     7

In [211]:
m.sample(3) # n random samples in our data frame

year   dept  time
0     1    cse     8
2     7    eee    12
2     3  civil    10

In [212]:
m.isnull()  # checks the null characters

year   dept   time
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [214]:
m.isna() # 

year   dept   time
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [219]:
# dropna() to drop/delete the null samples

AttributeError: module 'pandas' has no attribute 'drop'

In [220]:
dir(pd)

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'Interval',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseSeries',
 'Term',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt64Index',
 'WidePanel',
 '_DeprecatedModule',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_tslib',
 '_version',
 'api',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'descri

#### working with .csv files
- pd.read_csv(filename)

In [222]:
marks_df=pd.read_csv("marks.csv")
marks_df

Name  Year   Dept  Marks  Unnamed: 4  Unnamed: 5  Unnamed: 6  Subj1  Subj2  \
0    A     1    CSE     90         NaN         NaN         NaN     98     70   
1    B     3    ECE     87         NaN         NaN         NaN     70     88   
2    C     4    EEE     60         NaN         NaN         NaN     77     70   
3    D     2   MECH     49         NaN         NaN         NaN     95     77   
4    E     1  CIVIL     76         NaN         NaN         NaN     77     76   
5    F     3    CSE     56         NaN         NaN         NaN     82    100   
6    G     4    ECE     91         NaN         NaN         NaN     74     78   
7    H     3   MECH     45         NaN         NaN         NaN     79     97   
8    I     2  CIVIL     94         NaN         NaN         NaN     85     89   
9    J     1    EEE     60         NaN         NaN         NaN     90     73   

   Subj3  
0     94  
1     87  
2     97  
3     77  
4     97  
5     86  
6     88  
7     99  
8     92  
9     72

In [226]:
marks_df.isna()

Name   Year   Dept  Marks  Unnamed: 4  Unnamed: 5  Unnamed: 6  Subj1  \
0  False  False  False  False        True        True        True  False   
1  False  False  False  False        True        True        True  False   
2  False  False  False  False        True        True        True  False   
3  False  False  False  False        True        True        True  False   
4  False  False  False  False        True        True        True  False   
5  False  False  False  False        True        True        True  False   
6  False  False  False  False        True        True        True  False   
7  False  False  False  False        True        True        True  False   
8  False  False  False  False        True        True        True  False   
9  False  False  False  False        True        True        True  False   

   Subj2  Subj3  
0  False  False  
1  False  False  
2  False  False  
3  False  False  
4  False  False  
5  False  False  
6  False  False  
7  False  False  
8  False  False  
9  False  False

In [228]:
marks_df[marks_df.isna()]

Name  Year Dept  Marks  Unnamed: 4  Unnamed: 5  Unnamed: 6  Subj1  Subj2  \
0  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
1  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
2  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
3  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
4  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
5  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
6  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
7  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
8  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   
9  NaN   NaN  NaN    NaN         NaN         NaN         NaN    NaN    NaN   

   Subj3  
0    NaN  
1    NaN  
2    NaN  
3    NaN  
4    NaN  
5    NaN  
6    NaN  
7    NaN  
8    NaN  
9    NaN